#!/usr/bin/python -B

import os,pickle
from muse.Readwrite import Go2running
from muse.Control import Gen_Loop
from muse.Readwrite.ReadInput import indict

# BigDict: {nu: {ng: {enth: Supercell}}}
BigDict,nulist = Go2running.Go2running()

nu = int(indict['MinNum_PrimitiveCell'][0])
if 'MaxNum_PrimitiveCell' not in indict:
    max_prim = int(indict['MinNum_PrimitiveCell'][0])

else:
    max_prim = int(indict['MaxNum_PrimitiveCell'][0])

if int(indict['IfPickUp'][0]) == 1:
    RestartFile = open('.Restart','r')
    Restart_dict = pickle.load(RestartFile)
    Dict_nu_keys = Restart_dict.keys()
    nu = Dict_nu_keys[-1]

while nu <= max_prim:
    all_enthfile = open('../all-enthalpy-'+str(nu),'a')
    best_enthfile = open('../best-enthalpy-'+str(nu),'a')
    all_enthfile.write("#ng-nn:"+" "*9+"HM"+" "*7+"sg"+" "*6+"Enthalpy"+" "*8+"Volume"+" "*6+"Pressure\n")
    best_enthfile.write("#ng:"+" "*9+"HM"+" "*7+"sg"+" "*6+"Enthalpy"+" "*8+"Volume"+" "*6+"Pressure\n")
    all_enthfile.flush()
    best_enthfile.flush()
    all_enthfile.close()
    best_enthfile.close()

    nulist.append(nu)
    BigDict[nu]={}
    BigDict = Gen_Loop.Gen_Loop(nu,nulist,BigDict)

    nu += int(indict['StepNum_PrimitiveCell'][0])

os.chdir("..")
os.system("rm -rf optdir")
os.chdir("..")

r=1
while r < 1000:
    if not os.path.isdir("done%d"%r):
        os.system("mv running done%d"%r)
        break
    r +=1
